<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
// $config['base_url'] = 'http://192.168.1.221/apps';
$config['base_url'] = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$config['base_url'] .= "://".$_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']); 

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '.aspx';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'd-M-Y H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQCs4hvT5V6LXEql
pW3gLF7QmEt6HI5Ta2xdtSVPgBe26lvxs1h+RdAj/ivMUhjm1ZSiITK5CX449zO1
810fA+XLeLirGNP8wJM8uikHMf1GixHO6KKate6kynVCD1w+cVMQ1OOqbXk+fAEX
gj7Z9/sUR0wP4gfLvlI7mquvw985LWoekWInZBvEASvhYFuS6JBG6z+lFDDwwVwk
d5xjWDCQO1oOjUB4v6ZmtRAbFCCCK4RktLQZHQ83pjIK4ox4ffYrh6xyh4iW6OYP
Orl+2aQB1XI3QgkTPmS04E7h+k7V1q5UrD2Kz6sv+DmZhJKlobQXxV5sV0kbpGXU
nS8SdkETihztJzHBMeJPAwXx3MbmUpUsapeMy85nGqfjPnWhUEMZg1N/if3Ia8XD
n/1t0T3khM70SEzN33M5F/4fGuI7fCwsNHQBojAWHWjAptAwCGhgKloXp7sFGg48
/yYBgJDf2SVdPj5Kh0qMSLtihd7O3zLlEgYdwIpf+29QtYxK0MZUFLjc3LxwFZPa
+uJxnNmcELeKhan0UF65MeqfwXg+ybglj4y4JnQAiJBArPyYjQrGgzURstpvfDhK
U1qLDFlFxSlzXEOVSf89CP0UhaUw7Us7IZ4ASwB9zGm4Sv2WSeDj5xvb12bR7wEL
B1eAtbNPfWbcVpwrH9nDTL9KeyXigwIDAQABAoICAQCYPRhCNTZXRDNbwNyLzqbD
y4iThHf0j6FCt5SeeG7pnWDP652evH14ZIdPCnBxPV0AlHllJi3nnhAERsUW3cjK
r4j26gsrBK3jiQ8+DdA6AZbx/DvMPy9iIAK35GzXc9Ww+bdtya89zdbsS75rFQsd
pVcemW1CBlvFrwNG6RY19H8BYgbsJySoKlvowICDUpZSTTCjfq9GIw+v8UBe3zcM
m6dHLy255xJyWTlQjx29YvLX96SshMF0wL5KhYsrQ8i2NmguBpnKQlbszEqyoJbj
IoHMlTMGpifqe6gbKN+pQL4NRAuBpDPcLxsRzAOTJV1AnYXzo712QQOHAc+E02uj
hRneGNbYckF38KkzXA8IEMJkbJIBDdP3wu/7PIY/Ln5aTpgjLweGSYYzhO3cFxD9
PccHxbvlyutgQs7gadCKIJeGUSoLQK6VVA9jERMz4Tbsjtnm9NR8WQ/SbDBvMunR
22eBp79ViJKJWRLMhR3MdaZ0yFiFyApgzzHc1Be/8x3cYKkXOJDbIQNWmlwGvbli
cjp/SOZkhMxcgpSwDZG3OSgYNUIywO8TylP6XcZPFl6qq7kF/czLEMrDyF86p4sf
sBCp95KIyZpbMqjLenNF6j7d7wcng2/2ms7KbASUVcIRZcd/fD+zWALPiZrXiJOh
IUbD65ECpyKjF1KQgrWkwQKCAQEA3sLpjei9L1wqNxHJEMxiklsg//Xp+CUQPBSE
CLVzXbn4uy3WGCLzsVxXwcVcpBeikqTPGJ2G16/GJNU5PXiicK+7qGrjTGGBzMg7
YjRaiTwwQK9Ia090rHdw207SkTdKi2MsEK8TUiTbvMr4nlNe3YE70V63Leth1BIl
o8CycrKQctvF8zCWCQefG3pJMoun2xZprOnPdy9UKoJJ6H0G+p1yGsqN41phJb9V
I2Fjwv/OIXCkU2MZ535Ru2BSgRh8GmzGcnrvR29HgYSPVGXc6I/ISTOU3YN9o4L4
ZE/RInm5cJoIlNc78RRvw69zHCHf2m0NXVZy2naxlGH2ZJMRoQKCAQEAxq3wua9t
CcJjA5VtIE2gA03oYKc1jb4nhWbo//1sOoF1kv+pGjmX9w2CaAAt3RcMy8wfvpWH
eK2vixoV4WIA+1UEqtrIoWU1gzca+jn3CgahIrTUwEMM41Wwi1OCy0XQPhSbOc6X
De7/9JFk59Tjk9SdNJ4zN0NZDBNlDkVHzsorpJJnIMyqfgrkyv6YrhWeB9aAz6QC
dwPNPeADVHSclZG+2tJ68i+HPVe5T5u+WiuvTsLGH2dlj5cmsyNr3kfdzhkx3Wam
KQQ4awFzi5go6sGvR84a6d5i13uxU1lwECTQI88mjc+DbvIdCx+rvyBJWvI6BzXS
Ec898jyecQMJowKCAQEA2FH7L/2lSgp8TEIPOSrhRjMMlsOd04VagJ2DollikM/6
BPr7/zBh6gg8iEU6M3doPnOhUMwYl/dvuXD+Rv2Q8VEWMPSrig7eV5jSYglpKf+y
8/3Dm8HrEVhj1fRzcuV4lGdX8VOytYBpiqqoSEe5xeyrxCPwSr1boO+GccC9Cbjx
oThewEycRmSKU8qqrlUESjM3p9zdxWXGnAkt8IEJd/HRTscIhpHL6TYmXVdD46c5
6ytRyFBiZXU7tXRSal72lUqwY5eSKZKco9+wuEq6/XQzETLwCzSXm2OiBvejpZED
TZ+nWbKx2Oj5p9QHOniCw8BGzC8ZFaFRzUBcX0qaQQKCAQBuY2SV9vdRbdTPv+1i
/l5Cl73ePelOePHCeBxLZ0YD97wY0b3mGUvq83GaUUcqSU1Nynt0y+X6Uh5v3i18
DZTYEDPIrki9C9vArRRrJVuyEV7kRq7SqC53/TtbHipUwNRkOdTJOJTLJBjIjSQQ
f0N29rHl82Qnd175i6khVbMBHWlERifQnIa6A1l9xBmW1+H3HuJw/AJ2mAEoONgA
y83YeKMfN8Uh3PB6T8xhg/ouZYlA7I1iE3PlZSkWbT7YwPtnMK55AjieH38tTSAi
1ocdcEHwVn6zpGEsssgitFXEUn/m9YjJUBwJv7INZSpqxgib5GwDZ47xYEFd3vp1
diebAoIBAQCcI2Uz1XojBbk8MYd/LAQwo7q5KzX6b7JGPIIj+AXsxIYcLx/qa3UA
JRfoEgmBlR6TVAo5yWglUmzczEgU5P3GhpJe/53qCc86J6P88h69V5K1BXmZEVNG
Chbks5MF64Qha1XvOX6ywoyrA1Z26bqlOYCe0KnhmY4bGsPzuIKARNS41BmGEk+u
jktk6GW0DjGqXHCcqrGsTXZRyLkFHdsdxnzvejRn0+AeCx/1CUC7+vPnLVwftZkN
n2F40/DtgS5EB63ZlFO92tpq0r4BvxJSNdvE+oTKzYeFsluA+DDtEBJhXsfpRiXi
vAteLaItwCoZLlWWAAVTZfEBavPvRE/I';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
| 	by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|  when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 86400;
$config['sess_expire_on_close']	= TRUE;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 86400;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= ".api-hosting.ureg.asia";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';


/* End of file config.php */
/* Location: ./application/config/config.php */
